# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: local
    hooks:
      - id: ruff
        name: Format with Ruff
        entry: uv run ruff
        language: python
        types: [ python ]
        args: [ --config, backend/pyproject.toml, check, backend/yet_another_calendar ]
        additional_dependencies: [ uv ]