services:
  backend:
    build:
      context: ./backend
    container_name: calendar-backend
    restart: always
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
    volumes:
      - ./backend:/app/
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: calendar-frontend
    restart: always
    ports:
      - 3000:80

