services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: yet_another_calendar:${YET_ANOTHER_CALENDAR_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      YET_ANOTHER_CALENDAR_HOST: 0.0.0.0
      YET_ANOTHER_CALENDAR_REDIS_HOST: yet_another_calendar-redis

  redis:
    image: bitnami/redis:6.2.5
    hostname: "yet_another_calendar-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50


