name: test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==2.0.1
          $POETRY_HOME/bin/poetry --version
          cd backend/
          $POETRY_HOME/bin/poetry install
      - name: Run pytest
        run: |
          export POETRY_HOME=/opt/poetry
          cd backend/
          $POETRY_HOME/bin/poetry run pytest yet_another_calendar/tests/*